import type { Metadata, NextPage } from "next";
import { type HTMLAttributes, type PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import { supportedLngs } from "@/app/i18n/settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * /[lng]/** 아래 모든 페이지에 적용될 레이아웃에 전달할 URL Parameter
 */
interface RootLayoutParams {
  /**
   * 디렉토리 구조에 지정된 [lng] 파라미터
   */
  lng: HTMLAttributes<HTMLHtmlElement>["lang"];
}

/**
 * RootLayout 컴포넌트 props 목록 정의
 */
type RootLayoutProps = PropsWithChildren<{
  /**
   * URL Parameter
   */
  params: RootLayoutParams;
}>;

/**
 * SSG 빌드할 페이지 route 파라미터 목록 정의
 */
export const generateStaticParams = (): RootLayoutParams[] => {
  return supportedLngs.map(lng => ({ lng }));
};

/**
 * 페이지 전역 공통 레이아웃
 * @param children - 페이지에 표시할 내용
 * @param lang - URL Parameter 에 포함된 언어
 */
const RootLayout: NextPage<RootLayoutProps> = ({
  children,
  params: { lng },
}) => {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
};
export default RootLayout;
